name: auto build data

on:
  push:
    branches:
      - master
    paths:
      - data/**

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 13
      - name: build
#        env:
        run: |
          npm --version
          node --version
          npm ci
          npm run lint
          npm run build
      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
